services:
  frontend:
    build:
      context: .
      dockerfile: docker.dev/Dockerfile
    image: deskmint-frontend:1.0
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - deskmint_net

networks:
  deskmint_net:
    driver: bridge